export const ONEQR_INDUSTRIES = ['beauty', 'nail', 'food', 'shopping', 'health', 'mobility', 'home', 'finance', 'travel', 'education', 'events', 'family', 'business', 'community'] as const
export type OneQrIndustryId = typeof ONEQR_INDUSTRIES[number]

export interface OneQrArtworkConcept {
  id: string
  industryId: OneQrIndustryId
  brandingColor: string
  hoursColor: string
}

// Concept identity survives system language changes; localized names live in the locale tables.
export const ONEQR_CONCEPTS: OneQrArtworkConcept[] = [
  { id: 'beauty-nail', industryId: 'beauty', brandingColor: '#fce8f3', hoursColor: '#fce8f3' },
  { id: 'beauty-spa', industryId: 'beauty', brandingColor: '#f2f9ed', hoursColor: '#f2f9ed' },
  { id: 'beauty-barber', industryId: 'beauty', brandingColor: '#fff1dd', hoursColor: '#fff1dd' },
  { id: 'beauty-skincare', industryId: 'beauty', brandingColor: '#ffedf1', hoursColor: '#ffedf1' },
  { id: 'beauty-lash-couture', industryId: 'beauty', brandingColor: '#fff1e7', hoursColor: '#fff1e7' },
  { id: 'beauty-makeup-atelier', industryId: 'beauty', brandingColor: '#582732', hoursColor: '#582732' },
  { id: 'beauty-brow-bar', industryId: 'beauty', brandingColor: '#3c2418', hoursColor: '#3c2418' },
  { id: 'beauty-fragrance-studio', industryId: 'beauty', brandingColor: '#fff3da', hoursColor: '#fff3da' },
  { id: 'food-bistro', industryId: 'food', brandingColor: '#3e2522', hoursColor: '#3e2522' },
  { id: 'food-coffee', industryId: 'food', brandingColor: '#35251e', hoursColor: '#35251e' },
  { id: 'food-bakery', industryId: 'food', brandingColor: '#4a3456', hoursColor: '#4a3456' },
  { id: 'food-quick', industryId: 'food', brandingColor: '#44221c', hoursColor: '#44221c' },
  { id: 'shopping-retail', industryId: 'shopping', brandingColor: '#f6f0e7', hoursColor: '#f6f0e7' },
  { id: 'shopping-florist', industryId: 'shopping', brandingColor: '#fff0eb', hoursColor: '#fff0eb' },
  { id: 'shopping-boutique', industryId: 'shopping', brandingColor: '#f5f2e9', hoursColor: '#f5f2e9' },
  { id: 'shopping-market', industryId: 'shopping', brandingColor: '#fff4d6', hoursColor: '#fff4d6' },
  { id: 'shopping-fine-jewelry', industryId: 'shopping', brandingColor: '#f8f4e9', hoursColor: '#f8f4e9' },
  { id: 'shopping-artisan-ceramics', industryId: 'shopping', brandingColor: '#2f3933', hoursColor: '#2f3933' },
  { id: 'shopping-luxury-home', industryId: 'shopping', brandingColor: '#f6ebd9', hoursColor: '#f6ebd9' },
  { id: 'shopping-curated-gifts', industryId: 'shopping', brandingColor: '#51263b', hoursColor: '#51263b' },
  { id: 'health-dental', industryId: 'health', brandingColor: '#245457', hoursColor: '#245457' },
  { id: 'health-fitness', industryId: 'health', brandingColor: '#eef5ff', hoursColor: '#eef5ff' },
  { id: 'health-wellness', industryId: 'health', brandingColor: '#4b4237', hoursColor: '#4b4237' },
  { id: 'health-optical', industryId: 'health', brandingColor: '#e7f3ff', hoursColor: '#e7f3ff' },
  { id: 'health-pilates', industryId: 'health', brandingColor: '#f7efde', hoursColor: '#f7efde' },
  { id: 'health-physio', industryId: 'health', brandingColor: '#173c41', hoursColor: '#173c41' },
  { id: 'health-nutrition', industryId: 'health', brandingColor: '#fff1df', hoursColor: '#fff1df' },
  { id: 'health-skin', industryId: 'health', brandingColor: '#4c2735', hoursColor: '#4c2735' },
  { id: 'mobility-auto', industryId: 'mobility', brandingColor: '#f0f6ff', hoursColor: '#f0f6ff' },
  { id: 'mobility-detailing', industryId: 'mobility', brandingColor: '#edf7ff', hoursColor: '#edf7ff' },
  { id: 'mobility-bike', industryId: 'mobility', brandingColor: '#fff1d8', hoursColor: '#fff1d8' },
  { id: 'mobility-transit', industryId: 'mobility', brandingColor: '#f0f5ff', hoursColor: '#f0f5ff' },
  { id: 'mobility-electric', industryId: 'mobility', brandingColor: '#25443a', hoursColor: '#25443a' },
  { id: 'mobility-yacht', industryId: 'mobility', brandingColor: '#145362', hoursColor: '#145362' },
  { id: 'mobility-atelier', industryId: 'mobility', brandingColor: '#fff0dc', hoursColor: '#fff0dc' },
  { id: 'mobility-transfer', industryId: 'mobility', brandingColor: '#f1f6f8', hoursColor: '#f1f6f8' },
  { id: 'home-repair', industryId: 'home', brandingColor: '#fff2dd', hoursColor: '#fff2dd' },
  { id: 'home-cleaning', industryId: 'home', brandingColor: '#3f4c42', hoursColor: '#3f4c42' },
  { id: 'home-garden', industryId: 'home', brandingColor: '#f5f6dd', hoursColor: '#f5f6dd' },
  { id: 'home-interior', industryId: 'home', brandingColor: '#32291e', hoursColor: '#32291e' },
  { id: 'home-architecture', industryId: 'home', brandingColor: '#243f39', hoursColor: '#243f39' },
  { id: 'home-furniture', industryId: 'home', brandingColor: '#fff2df', hoursColor: '#fff2df' },
  { id: 'home-smart', industryId: 'home', brandingColor: '#f1f8ff', hoursColor: '#f1f8ff' },
  { id: 'home-renovation', industryId: 'home', brandingColor: '#29483e', hoursColor: '#29483e' },
  { id: 'finance-advisor', industryId: 'finance', brandingColor: '#f3eee3', hoursColor: '#f3eee3' },
  { id: 'finance-legal', industryId: 'finance', brandingColor: '#fff2d9', hoursColor: '#fff2d9' },
  { id: 'finance-property', industryId: 'finance', brandingColor: '#52473a', hoursColor: '#52473a' },
  { id: 'finance-accounting', industryId: 'finance', brandingColor: '#263b38', hoursColor: '#263b38' },
  { id: 'finance-private-banking', industryId: 'finance', brandingColor: '#f6efe1', hoursColor: '#f6efe1' },
  { id: 'finance-wealth-planning', industryId: 'finance', brandingColor: '#253a35', hoursColor: '#253a35' },
  { id: 'finance-insurance-studio', industryId: 'finance', brandingColor: '#f1f7f4', hoursColor: '#f1f7f4' },
  { id: 'finance-home-finance', industryId: 'finance', brandingColor: '#46352a', hoursColor: '#46352a' },
  { id: 'travel-hotel', industryId: 'travel', brandingColor: '#fff0d9', hoursColor: '#fff0d9' },
  { id: 'travel-resort', industryId: 'travel', brandingColor: '#173e46', hoursColor: '#173e46' },
  { id: 'travel-tour', industryId: 'travel', brandingColor: '#fff2e4', hoursColor: '#fff2e4' },
  { id: 'travel-camping', industryId: 'travel', brandingColor: '#f4e8d4', hoursColor: '#f4e8d4' },
  { id: 'travel-atelier', industryId: 'travel', brandingColor: '#fff1e9', hoursColor: '#fff1e9' },
  { id: 'travel-alpine', industryId: 'travel', brandingColor: '#21454a', hoursColor: '#21454a' },
  { id: 'travel-canyon', industryId: 'travel', brandingColor: '#613f35', hoursColor: '#613f35' },
  { id: 'travel-fjord', industryId: 'travel', brandingColor: '#f0f7f7', hoursColor: '#f0f7f7' },
  { id: 'education-academy', industryId: 'education', brandingColor: '#fff1d5', hoursColor: '#fff1d5' },
  { id: 'education-language', industryId: 'education', brandingColor: '#23414c', hoursColor: '#23414c' },
  { id: 'education-music', industryId: 'education', brandingColor: '#ffe9d4', hoursColor: '#ffe9d4' },
  { id: 'education-skills', industryId: 'education', brandingColor: '#38291d', hoursColor: '#38291d' },
  { id: 'education-culinary', industryId: 'education', brandingColor: '#fff0df', hoursColor: '#fff0df' },
  { id: 'education-photography', industryId: 'education', brandingColor: '#294650', hoursColor: '#294650' },
  { id: 'education-dance', industryId: 'education', brandingColor: '#fce9ef', hoursColor: '#fce9ef' },
  { id: 'education-steam', industryId: 'education', brandingColor: '#21515c', hoursColor: '#21515c' },
  { id: 'events-concert', industryId: 'events', brandingColor: '#fff1e7', hoursColor: '#fff1e7' },
  { id: 'events-cinema', industryId: 'events', brandingColor: '#fff0d8', hoursColor: '#fff0d8' },
  { id: 'events-wedding', industryId: 'events', brandingColor: '#503c2d', hoursColor: '#503c2d' },
  { id: 'events-festival', industryId: 'events', brandingColor: '#f2eaff', hoursColor: '#f2eaff' },
  { id: 'events-gala', industryId: 'events', brandingColor: '#fff0df', hoursColor: '#fff0df' },
  { id: 'events-summit', industryId: 'events', brandingColor: '#173e57', hoursColor: '#173e57' },
  { id: 'events-theater', industryId: 'events', brandingColor: '#fff2e5', hoursColor: '#fff2e5' },
  { id: 'events-chefs-table', industryId: 'events', brandingColor: '#2d493c', hoursColor: '#2d493c' },
  { id: 'family-pet', industryId: 'family', brandingColor: '#4b321f', hoursColor: '#4b321f' },
  { id: 'family-grooming', industryId: 'family', brandingColor: '#234542', hoursColor: '#234542' },
  { id: 'family-childcare', industryId: 'family', brandingColor: '#334b5a', hoursColor: '#334b5a' },
  { id: 'family-play', industryId: 'family', brandingColor: '#393c4e', hoursColor: '#393c4e' },
  { id: 'family-portrait', industryId: 'family', brandingColor: '#fff0e9', hoursColor: '#fff0e9' },
  { id: 'family-maternity', industryId: 'family', brandingColor: '#294737', hoursColor: '#294737' },
  { id: 'family-celebration', industryId: 'family', brandingColor: '#fff2e6', hoursColor: '#fff2e6' },
  { id: 'family-senior-care', industryId: 'family', brandingColor: '#234b54', hoursColor: '#234b54' },
  { id: 'business-digital', industryId: 'business', brandingColor: '#f1f4ff', hoursColor: '#f1f4ff' },
  { id: 'business-consulting', industryId: 'business', brandingColor: '#3b2b23', hoursColor: '#3b2b23' },
  { id: 'business-cowork', industryId: 'business', brandingColor: '#2a403b', hoursColor: '#2a403b' },
  { id: 'business-it', industryId: 'business', brandingColor: '#e5fbfb', hoursColor: '#e5fbfb' },
  { id: 'business-architecture-studio', industryId: 'business', brandingColor: '#243943', hoursColor: '#243943' },
  { id: 'business-hospitality-operations', industryId: 'business', brandingColor: '#fff1df', hoursColor: '#fff1df' },
  { id: 'business-creative-production', industryId: 'business', brandingColor: '#f6eee7', hoursColor: '#f6eee7' },
  { id: 'business-sustainable-manufacturing', industryId: 'business', brandingColor: '#29473a', hoursColor: '#29473a' },
  { id: 'community-volunteer', industryId: 'community', brandingColor: '#314023', hoursColor: '#314023' },
  { id: 'community-charity', industryId: 'community', brandingColor: '#433224', hoursColor: '#433224' },
  { id: 'community-library', industryId: 'community', brandingColor: '#fff3dc', hoursColor: '#fff3dc' },
  { id: 'community-arts', industryId: 'community', brandingColor: '#173b50', hoursColor: '#173b50' },
  { id: 'community-heritage', industryId: 'community', brandingColor: '#fff2d8', hoursColor: '#fff2d8' },
  { id: 'community-youth-sports', industryId: 'community', brandingColor: '#173e35', hoursColor: '#173e35' },
  { id: 'community-makerspace', industryId: 'community', brandingColor: '#edfbf6', hoursColor: '#edfbf6' },
  { id: 'community-kitchen', industryId: 'community', brandingColor: '#653721', hoursColor: '#653721' },
  { id: '01', industryId: 'nail', brandingColor: '#8b652d', hoursColor: '#543914' },
  { id: '02', industryId: 'nail', brandingColor: '#f0d77f', hoursColor: '#f0d77f' },
  { id: '03', industryId: 'nail', brandingColor: '#a05256', hoursColor: '#772e3b' },
  { id: '04', industryId: 'nail', brandingColor: '#273f30', hoursColor: '#273f30' },
  { id: '05', industryId: 'nail', brandingColor: '#cdf8fc', hoursColor: '#cdf8fc' },
  { id: '06', industryId: 'nail', brandingColor: '#202020', hoursColor: '#202020' },
  { id: '07', industryId: 'nail', brandingColor: '#8b652d', hoursColor: '#17130c' },
  { id: '08', industryId: 'nail', brandingColor: '#12477b', hoursColor: '#12477b' },
]
