// DEMO CONTENT: This file contains static mock data for PO review.
// There is no backend yet for Events, Learning, and Jobs.
// These will be replaced with real API data later.
// DO NOT save to Supabase, create tables, or call APIs for this data.

export const demoEvents = [
  {
    id: 'e1',
    title: 'Workshop: Kỹ thuật đắp Gel-X chuẩn form',
    date: '2026-08-15',
    location: 'Houston, TX',
    attendees: 42,
  },
  {
    id: 'e2',
    title: 'Hội thảo chủ Salon: Quản lý thợ và tăng doanh thu',
    date: '2026-08-22',
    location: 'Online (Zoom)',
    attendees: 156,
  },
  {
    id: 'e3',
    title: 'Nail Art Masterclass: Xu hướng Thu Đông 2026',
    date: '2026-09-05',
    location: 'Atlanta, GA',
    attendees: 28,
  }
];

export const demoLearning = [
  {
    id: 'l1',
    title: 'Khoá học đắp bột cơ bản cho người mới bắt đầu',
    author: 'Master Kelly',
    duration: '12 video (4 giờ)',
    rating: 4.8,
  },
  {
    id: 'l2',
    title: 'Kỹ thuật vẽ 3D nổi và đính đá chuyên nghiệp',
    author: 'Jimmy Nguyen',
    duration: '8 video (2.5 giờ)',
    rating: 4.9,
  },
  {
    id: 'l3',
    title: 'Tiếng Anh giao tiếp cơ bản ngành Nail',
    author: 'Nexora Academy',
    duration: '20 video (5 giờ)',
    rating: 4.7,
  }
];

export type DemoJob = {
  id: string
  postKind: 'seeking' | 'hiring'
  title: string
  salon: string | null
  location: string
  salary: string
  employmentType: 'Full-time' | 'Part-time'
  status: 'open' | 'filled' | 'closed'
  urgent?: boolean
  posted: string
  posterName: string
  posterRole: string
  experience: string
  skills?: string[]
  availability?: string
  payModel?: string
  support?: string[]
  image: string
  description: string
  ownerPersonaId: string | null
  /** Real-account persona behind this posting, for routing "Nhắn tin" into the
   * real DM system (src/components/community/jobChatTarget.ts). Optional —
   * seeds j1–j4 set it — one per real demo account (Kayla, David, Linh, Jessica); jobs created in-session fall back to
   * `ownerPersonaId` at the call site instead of here. */
  posterPersonaId?: 'kayla' | 'jessica' | 'linh' | 'david'
  /** Poster contact details, shown on every post that has them (with or without
   * a Nexora account).
   * Mock values (555 numbers, example.com) — TODO: map from the Nailhub.ai job
   * API once it is wired (T14); its field names are not confirmed yet. */
  contactPhone?: string
  contactEmail?: string
}

export const DEFAULT_JOB_IMAGE = '/assets/images/marketing/nail/nail_spa_treatment.jpg'

// postKind: 'hiring' (chủ tiệm đăng tuyển) | 'seeking' (thợ đăng tìm việc) — tách riêng
// khỏi employmentType (Full-time/Part-time) để không đè nghĩa 1 field cho 2 khái niệm khác nhau.
// ownerPersonaId: null cho tin mẫu có sẵn; tin do demo "Đăng tin" tạo ra sẽ gắn id persona
// đang đăng nhập để demo được luồng "Bài của tôi" (sửa/xoá/đổi trạng thái).
export const demoJobs: DemoJob[] = [
  {
    id: 'j1',
    postKind: 'hiring',
    posterPersonaId: 'kayla',
    title: 'Tuyển thợ bột / thợ tay chân nước bao lương',
    salon: 'Luxury Nails & Spa',
    location: 'Houston, TX',
    salary: '$1,200 - $1,500/tuần',
    employmentType: 'Full-time',
    status: 'open',
    posted: '2 ngày trước',
    posterName: 'Kayla Le',
    posterRole: 'Chủ salon',
    contactPhone: '(713) 555-0101',
    contactEmail: 'luxurynails@example.com',
    experience: '2+ năm kinh nghiệm',
    image: DEFAULT_JOB_IMAGE,
    description: 'Luxury Nails & Spa cần thợ bột và thợ tay chân nước có tay nghề ổn định, phục vụ khách quen là chính. Tiệm đông khách quanh năm, bao lương tuần đầu để thợ mới quen khách trước khi tính ăn chia.',
    ownerPersonaId: 'kayla',
  },
  {
    id: 'j2',
    postKind: 'hiring',
    posterPersonaId: 'david',
    title: 'Cần thợ xuyên bang, có chỗ ở cho thợ',
    salon: 'Cali Beauty Nails',
    location: 'Dallas, TX',
    salary: 'Ăn chia 6/4',
    employmentType: 'Full-time',
    status: 'open',
    urgent: true,
    posted: '5 giờ trước',
    posterName: 'David Pham',
    posterRole: 'Chủ salon',
    contactPhone: '(214) 555-0102',
    contactEmail: 'davidpham@example.com',
    experience: 'Không yêu cầu kinh nghiệm',
    image: '/assets/images/marketing/nail/nail_rose_quartz.jpg',
    description: 'Cali Beauty Nails ở Dallas cần thợ xuyên bang, có chỗ ở miễn phí cho thợ mới chuyển tới trong 2 tuần đầu. Tiệm khu Mỹ trắng, khách tip cao, cần thợ chăm chỉ và giao tiếp cơ bản.',
    ownerPersonaId: null,
  },
  {
    id: 'j3',
    postKind: 'hiring',
    posterPersonaId: 'linh',
    title: 'Tuyển thợ phụ (Receptionist) biết tiếng Anh',
    salon: 'Bella Salon',
    location: 'Austin, TX',
    salary: '$700 - $900/tuần',
    employmentType: 'Part-time',
    status: 'open',
    posted: '1 ngày trước',
    posterName: 'Linh Tran',
    posterRole: 'Quản lý',
    contactPhone: '(512) 555-0103',
    contactEmail: 'bellasalon@example.com',
    experience: 'Ưu tiên có kinh nghiệm đón khách',
    image: '/assets/images/marketing/nail/nail_zen_minimalist.jpg',
    description: 'Bella Salon cần thợ phụ/receptionist biết tiếng Anh giao tiếp cơ bản để đón khách, đặt lịch, và hỗ trợ khu vực sơn. Lịch làm linh động, phù hợp học sinh/sinh viên làm part-time.',
    ownerPersonaId: null,
  },
  {
    id: 'j4',
    postKind: 'seeking',
    posterPersonaId: 'jessica',
    title: 'Thợ nail 5 năm kinh nghiệm tìm chỗ làm ổn định',
    salon: null,
    location: 'Houston, TX',
    salary: 'Mong muốn 60/40 hoặc lương cứng $900+/tuần',
    employmentType: 'Full-time',
    status: 'open',
    posted: '4 giờ trước',
    posterName: 'Jessica Nguyen',
    posterRole: 'Thợ nail',
    contactPhone: '(713) 555-0104',
    contactEmail: 'jessicanails@example.com',
    experience: '5 năm kinh nghiệm bột & dip',
    image: '/assets/images/marketing/nail/nail_art_luxury.jpg',
    description: 'Thợ nail 5 năm kinh nghiệm bột và dip, đang tìm tiệm ổn định lâu dài ở khu Houston. Có thể đi làm ngay, ưu tiên tiệm đông khách quen, môi trường làm việc thoải mái.',
    ownerPersonaId: 'jessica',
  },
  {
    id: 'j5',
    postKind: 'hiring',
    title: 'Cần gấp thợ bột bao lương $1,500 - $1,800/tuần',
    salon: 'Golden Nails & Spa',
    location: 'Dallas, TX',
    salary: '$1,500 - $1,800/tuần',
    employmentType: 'Full-time',
    status: 'open',
    urgent: true,
    posted: '3 giờ trước',
    posterName: 'Tony Dang',
    posterRole: 'Chủ tiệm',
    contactPhone: '(214) 555-0105',
    contactEmail: 'tonydang@example.com',
    experience: '3+ năm kinh nghiệm',
    skills: ['Thợ bột', 'Gel-X', 'Dip'],
    availability: 'Đi làm ngay',
    payModel: 'Bao lương hoặc ăn chia 6/4 tuỳ tay nghề',
    support: ['Lịch linh hoạt', 'Hỗ trợ chỗ ở', 'Đào tạo thêm'],
    image: '/assets/images/marketing/nail/nail_glam_french.jpg',
    description: 'Tiệm Golden Nails khu trung tâm thương mại Dallas, lượng khách ổn định quanh năm. Cần 2 thợ bột lành nghề làm toàn thời gian, bao lương tuần đầu nếu thợ cần thời gian làm quen. Tiệm có phòng riêng cho thợ ở xa chuyển về.',
    ownerPersonaId: null,
  },
  {
    id: 'j6',
    postKind: 'seeking',
    title: 'Thợ nail chuyên Gel-X & Nail Art tìm tiệm tip cao',
    salon: null,
    location: 'Austin, TX',
    salary: 'Mong muốn ăn chia 6/4 hoặc lương bảo đảm',
    employmentType: 'Full-time',
    status: 'open',
    posted: '6 giờ trước',
    posterName: 'Ngọc Tran',
    posterRole: 'Thợ nail',
    contactPhone: '(512) 555-0106',
    experience: '4 năm kinh nghiệm form & vẽ nổi',
    skills: ['Gel-X', 'Vẽ 3D', 'Đính đá', 'Ombre'],
    availability: 'Có thể đi làm từ thứ Hai tuần tới',
    payModel: 'Ăn chia 6/4',
    image: '/assets/images/marketing/nail/nail_summer_pop.jpg',
    description: 'Em có 4 năm kinh nghiệm chuyên đắp form Gel-X và vẽ móng theo mẫu Instagram/Pinterest. Tiếng Anh giao tiếp tốt, vui vẻ với khách. Cần tìm tiệm khu trẻ trung năng động ở Austin, khách chịu chi và tip tốt.',
    ownerPersonaId: null,
  },
  {
    id: 'j7',
    postKind: 'hiring',
    title: 'Tuyển cặp vợ chồng thợ nail hoặc 2 thợ tay chân nước',
    salon: 'Star Nails Lounge',
    location: 'Houston, TX',
    salary: '$1,100 - $1,400/người/tuần',
    employmentType: 'Full-time',
    status: 'open',
    posted: '1 ngày trước',
    posterName: 'Andy Le',
    posterRole: 'Chủ tiệm',
    contactPhone: '(713) 555-0107',
    contactEmail: 'andyle@example.com',
    experience: 'Biết làm tay chân nước, massage foot',
    skills: ['Tay chân nước', 'Gel', 'Dipping'],
    availability: 'Full-time 6 ngày/tuần',
    payModel: 'Bao lương 6 ngày hoặc ăn chia',
    support: ['Lịch linh hoạt', 'Hỗ trợ chỗ ở'],
    image: DEFAULT_JOB_IMAGE,
    description: 'Tiệm Star Nails ở Tây Houston cần cặp vợ chồng hoặc 2 thợ tay chân nước, dip. Tiệm không khí gia đình, vui vẻ, không tranh giành turn. Chủ bao lương quanh năm $1,100 - $1,400/tuần tuỳ theo khả năng làm việc.',
    ownerPersonaId: null,
  },
  {
    id: 'j8',
    postKind: 'seeking',
    title: 'Thợ phụ tìm việc Part-time cuối tuần (T6, T7, CN)',
    salon: null,
    location: 'Dallas, TX',
    salary: '$800 - $1,000/tuần',
    employmentType: 'Part-time',
    status: 'open',
    posted: '1 ngày trước',
    posterName: 'Linda Vu',
    posterRole: 'Thợ nail part-time',
    contactEmail: 'lindavu@example.com',
    experience: '1 năm làm nước và sơn gel',
    skills: ['Tay chân nước', 'Sơn gel', 'Cắt da sạch'],
    availability: 'Thứ 6, thứ 7 và Chủ nhật',
    payModel: 'Lương giờ + tip',
    image: '/assets/images/marketing/nail/nail_rose_quartz.jpg',
    description: 'Em là sinh viên đang tìm việc làm thêm vào các ngày cuối tuần (thứ 6, 7, CN). Biết cắt da sạch, sơn gel tròn khoé, làm foot massage chu đáo. Giao tiếp tiếng Anh lưu loát, nhanh nhẹn và đúng giờ.',
    ownerPersonaId: null,
  },
  {
    id: 'j9',
    postKind: 'hiring',
    title: 'Tuyển thợ bột & dip tiệm Mỹ trắng khu Bellaire',
    salon: 'Bellaire Nail Boutique',
    location: 'Houston, TX',
    salary: '$1,300 - $1,700/tuần',
    employmentType: 'Full-time',
    status: 'open',
    urgent: true,
    posted: '2 ngày trước',
    posterName: 'Kathy Vo',
    posterRole: 'Quản lý',
    contactPhone: '(713) 555-0109',
    contactEmail: 'kathyvo@example.com',
    experience: '2+ năm kinh nghiệm bột',
    skills: ['Bột pink & white', 'Dipping powder', 'Ombre'],
    availability: 'Đi làm ngay',
    payModel: 'Ăn chia 6/4, bao lương mùa chậm',
    support: ['Lịch linh hoạt', 'Đào tạo thêm'],
    image: '/assets/images/marketing/nail/nail_art_luxury.jpg',
    description: 'Tiệm khu Bellaire sầm uất, 100% khách Mỹ trắng văn phòng, tip hậu hĩnh. Cần gấp thợ bột giỏi pink & white, dip mỏng tự nhiên. Có máy dũa xịn, bàn hút bụi từng trạm làm việc, môi trường sạch sẽ không mùi hoá chất.',
    ownerPersonaId: null,
  },
  {
    id: 'j10',
    postKind: 'hiring',
    title: 'Cần thợ chuyên vẽ móng nghệ thuật & đính đá',
    salon: 'Oasis Luxury Spa',
    location: 'Austin, TX',
    salary: '$1,400 - $2,000/tuần',
    employmentType: 'Full-time',
    status: 'open',
    posted: '3 ngày trước',
    posterName: 'Brian Nguyen',
    posterRole: 'Chủ salon',
    contactPhone: '(512) 555-0110',
    contactEmail: 'briannguyen@example.com',
    experience: 'Kỹ thuật vẽ cọ nét, 3D',
    skills: ['Nail Art', 'Đính đá Swarovski', 'Gel-X'],
    availability: 'Full-time',
    payModel: 'Ăn chia 6/4 + thưởng doanh số',
    support: ['Đào tạo thêm'],
    image: '/assets/images/marketing/nail/nail_summer_pop.jpg',
    description: 'Oasis Luxury Spa cần thợ có khiếu thẩm mỹ cao, thành thạo vẽ cọ nét và đính đá phong cách hiện đại. Tiệm có nguồn khách trẻ đặt lịch trước rất đông, giá dịch vụ cao, tip 20-30%. Thu nhập từ $1,400 đến trên $2,000/tuần.',
    ownerPersonaId: null,
  },
  {
    id: 'j11',
    postKind: 'hiring',
    title: 'Tuyển thợ nail làm việc tại The Domain Austin',
    salon: 'Domain Nails Bar',
    location: 'Austin, TX',
    salary: '$1,200 - $1,500/tuần',
    employmentType: 'Full-time',
    status: 'filled',
    posted: '4 ngày trước',
    posterName: 'Chloe Hoang',
    posterRole: 'Chủ salon',
    contactPhone: '(512) 555-0111',
    contactEmail: 'chloehoang@example.com',
    experience: '1-2 năm kinh nghiệm',
    skills: ['Dip', 'Gel-X', 'Tay chân nước'],
    availability: 'Thoả thuận',
    payModel: 'Bao lương hoặc ăn chia 6/4',
    image: '/assets/images/marketing/nail/nail_zen_minimalist.jpg',
    description: 'Tiệm nằm trong khu mua sắm cao cấp The Domain Austin. Vị trí đắc địa, khách sang trọng. Đã tuyển đủ vị trí tuần này, nhận hồ sơ dự phòng cho đợt mở rộng tháng sau.',
    ownerPersonaId: null,
  },
  {
    id: 'j12',
    postKind: 'seeking',
    title: 'Thợ nail lớn tuổi cẩn thận tìm việc chân tay nước bao lương',
    salon: null,
    location: 'Houston, TX',
    salary: 'Bao lương $900 - $1,000/tuần',
    employmentType: 'Full-time',
    status: 'open',
    posted: '3 ngày trước',
    posterName: 'Co Lan',
    posterRole: 'Thợ nail',
    contactPhone: '(713) 555-0112',
    experience: '10+ năm chân tay nước',
    skills: ['Tay chân nước', 'Sơn thường', 'Massage'],
    availability: 'Đi làm ngay các ngày trong tuần',
    payModel: 'Lương bao cố định',
    image: DEFAULT_JOB_IMAGE,
    description: 'Cô Lan 52 tuổi, làm nail hơn 10 năm chuyên tay chân nước, chà gót êm, massage chân khách rất thích. Tính tình hiền lành, chịu khó, sạch sẽ. Mong muốn tìm tiệm đàng hoàng, chủ và đồng nghiệp vui vẻ, bao lương ổn định.',
    ownerPersonaId: null,
  },
  {
    id: 'j13',
    postKind: 'hiring',
    title: 'Cần sang nhượng tiệm nail 8 bàn 8 ghế hoặc tìm đối tác quản lý',
    salon: 'Diamond Nails & Spa',
    location: 'Dallas, TX',
    salary: 'Thoả thuận trực tiếp',
    employmentType: 'Full-time',
    status: 'open',
    urgent: true,
    posted: '5 ngày trước',
    posterName: 'Henry Pham',
    posterRole: 'Chủ salon',
    contactPhone: '(214) 555-0113',
    contactEmail: 'henrypham@example.com',
    experience: 'Quản lý tiệm hoặc thợ chính',
    skills: ['Quản lý salon', 'Thợ bột chính'],
    availability: 'Có thể tiếp quản ngay',
    payModel: 'Hợp đồng ăn chia / Cổ phần',
    support: ['Hỗ trợ chỗ ở', 'Lịch linh hoạt'],
    image: '/assets/images/marketing/nail/nail_glam_french.jpg',
    description: 'Vì lý do gia đình chuyển bang, cần tìm thợ chính có kinh nghiệm lên làm quản lý hoặc sang nhượng lại tiệm 8 bàn 8 ghế tại Dallas. Tiệm đang hoạt động tốt với hơn 1,200 khách quen trong hệ thống POS. Giá cả thương lượng hợp lý.',
    ownerPersonaId: null,
  },
  {
    id: 'j14',
    postKind: 'seeking',
    title: 'Thợ bột Nam tay nghề cứng tìm tiệm đông khách ở Dallas',
    salon: null,
    location: 'Dallas, TX',
    salary: 'Ăn chia 6/4 hoặc bao lương $1,600+/tuần',
    employmentType: 'Full-time',
    status: 'closed',
    posted: '1 tuần trước',
    posterName: 'Minh Vu',
    posterRole: 'Thợ nail',
    contactPhone: '(214) 555-0114',
    contactEmail: 'minhvu@example.com',
    experience: '7 năm kinh nghiệm làm bột salon lớn',
    skills: ['Bột nhúng', 'Đắp móng úp', 'Form coffin & stiletto'],
    availability: 'Đã nhận việc',
    payModel: 'Ăn chia 6/4',
    image: '/assets/images/marketing/nail/nail_art_luxury.jpg',
    description: 'Thợ nam 32 tuổi tay nghề bột cứng, làm nhanh và chuẩn form coffin, almond, stiletto. Đã tìm được tiệm ưng ý, cảm ơn mọi người đã liên hệ.',
    ownerPersonaId: null,
  },
  {
    id: 'j15',
    postKind: 'hiring',
    title: 'Tuyển thợ chân tay nước tiệm mới khai trương',
    salon: 'Pearl Nails & Lounge',
    location: 'Houston, TX',
    salary: '$1,000 - $1,200/tuần',
    employmentType: 'Full-time',
    status: 'open',
    posted: '6 ngày trước',
    posterName: 'Jenny Lam',
    posterRole: 'Chủ salon',
    contactPhone: '(713) 555-0115',
    contactEmail: 'jennylam@example.com',
    experience: '1+ năm kinh nghiệm',
    skills: ['Tay chân nước', 'Sơn gel'],
    availability: 'Đi làm ngay',
    payModel: 'Bao lương 3 tháng đầu',
    image: '/assets/images/marketing/nail/nail_rose_quartz.jpg',
    description: 'Pearl Nails & Lounge mới khai trương khu Katy, cần 3 thợ chân tay nước. Bao lương 3 tháng đầu trong lúc tiệm xây dựng khách quen, ghế spa mới, không gian rộng rãi.',
    ownerPersonaId: null,
  },
  {
    id: 'j16',
    postKind: 'seeking',
    title: 'Thợ bột nữ tìm tiệm part-time buổi tối',
    salon: null,
    location: 'Austin, TX',
    salary: '$600 - $800/tuần',
    employmentType: 'Part-time',
    status: 'open',
    posted: '1 tuần trước',
    posterName: 'Vy Tran',
    posterRole: 'Thợ nail',
    contactPhone: '(512) 555-0116',
    contactEmail: 'vytran@example.com',
    experience: '3 năm kinh nghiệm bột',
    skills: ['Bột', 'Dip', 'Sơn gel'],
    availability: 'Tối thứ 2 – thứ 6',
    payModel: 'Ăn chia 6/4',
    image: '/assets/images/marketing/nail/nail_zen_minimalist.jpg',
    description: 'Em làm bột 3 năm, ban ngày đi học nên cần tiệm part-time buổi tối các ngày trong tuần ở Austin. Làm nhanh, sạch sẽ, giao tiếp tiếng Anh ổn.',
    ownerPersonaId: null,
  },
  {
    id: 'j17',
    postKind: 'hiring',
    title: 'Cần thợ eyelash & wax kiêm làm nail',
    salon: 'Glow Beauty Bar',
    location: 'Dallas, TX',
    salary: 'Thỏa thuận',
    employmentType: 'Full-time',
    status: 'open',
    posted: '1 tuần trước',
    posterName: 'Peter Ho',
    posterRole: 'Quản lý',
    contactPhone: '(214) 555-0117',
    experience: 'Có chứng chỉ eyelash là lợi thế',
    skills: ['Eyelash', 'Wax', 'Tay chân nước'],
    availability: 'Full-time',
    payModel: 'Lương cứng + hoa hồng dịch vụ',
    support: ['Đào tạo thêm'],
    image: '/assets/images/marketing/nail/nail_glam_french.jpg',
    description: 'Glow Beauty Bar cần 1 thợ làm eyelash và wax, rảnh thì phụ làm nail. Tiệm có sẵn khách đặt lịch online, hỗ trợ học chứng chỉ eyelash nếu chưa có.',
    ownerPersonaId: null,
  },
  {
    id: 'j18',
    postKind: 'seeking',
    title: 'Cặp vợ chồng thợ nail tìm tiệm có chỗ ở',
    salon: null,
    location: 'Houston, TX',
    salary: '$2,000 - $2,400/tuần',
    employmentType: 'Full-time',
    status: 'open',
    posted: '2 tuần trước',
    posterName: 'Quang & Thu',
    posterRole: 'Thợ nail',
    contactEmail: 'quangthu@example.com',
    experience: '6 năm kinh nghiệm (cả hai)',
    skills: ['Bột', 'Gel-X', 'Tay chân nước'],
    availability: 'Có thể chuyển tới trong 2 tuần',
    payModel: 'Bao lương cho cả hai',
    image: DEFAULT_JOB_IMAGE,
    description: 'Hai vợ chồng đều làm nail 6 năm, chồng làm bột, vợ làm tay chân nước và Gel-X. Đang ở bang khác, tìm tiệm khu Houston có hỗ trợ chỗ ở để chuyển tới làm lâu dài.',
    ownerPersonaId: null,
  },
];

export const JOB_POST_KINDS = [
  { value: 'seeking', label: 'Tìm việc' },
  { value: 'hiring', label: 'Tuyển thợ' },
];

export const JOB_LOCATIONS = ['Tất cả khu vực', 'Houston, TX', 'Dallas, TX', 'Austin, TX'];
