/**
 * Resolves a backend/merchant-supplied Lucide icon *name* to a real component.
 *
 * `CustomIcon` is free text on the entity (`varchar(40)`), so this must be an
 * allowlist, not a dynamic import: an unknown name falls back to a neutral
 * square rather than crashing the tile grid. Add names here when the backend
 * registry starts emitting them.
 */
import {
  Award,
  BadgeDollarSign,
  Bell,
  Bike,
  Bot,
  Briefcase,
  Building2,
  Cake,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Camera,
  Car,
  Check,
  CheckCircle2,
  ChefHat,
  Clock,
  Coffee,
  CreditCard,
  Crown,
  DollarSign,
  ExternalLink,
  Facebook,
  Flower2,
  Gamepad2,
  Gift,
  Globe2,
  HandCoins,
  Heart,
  Home,
  Image as ImageIcon,
  Instagram,
  LayoutDashboard,
  LayoutList,
  Link2,
  Linkedin,
  List,
  Mail,
  Map as MapIcon,
  MapPin,
  Megaphone,
  MessageCircle,
  Music,
  Package,
  Paintbrush,
  Percent,
  Phone,
  QrCode,
  Receipt,
  Rocket,
  ScanLine,
  Settings,
  Settings2,
  Share2,
  ShoppingBag,
  Sparkles,
  Square,
  Star,
  Store,
  Tag,
  ThumbsUp,
  Ticket,
  Trophy,
  Truck,
  Tv,
  User,
  UserCog,
  Users,
  Utensils,
  Video,
  Wallet,
  Wand2,
  Wifi,
  Wrench,
  Youtube,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/**
 * Includes the newer Lucide names the backend registry emits
 * (`circle-check`, `square-arrow-out-up-right`, `user-round`, `users-round`),
 * aliased onto the equivalents that exist in this repo's lucide-react 0.344.
 * Without the aliases those keys would fall through to a blank square.
 */
const ICONS: Record<string, LucideIcon> = {
  award: Award,
  'badge-dollar-sign': BadgeDollarSign,
  bell: Bell,
  bike: Bike,
  bot: Bot,
  briefcase: Briefcase,
  'building-2': Building2,
  cake: Cake,
  'calendar-check': CalendarCheck,
  'calendar-clock': CalendarClock,
  'calendar-days': CalendarDays,
  camera: Camera,
  car: Car,
  check: Check,
  'check-circle-2': CheckCircle2,
  'chef-hat': ChefHat,
  'circle-check': CheckCircle2,
  'circle-check-big': CheckCircle2,
  clock: Clock,
  coffee: Coffee,
  'credit-card': CreditCard,
  crown: Crown,
  'dollar-sign': DollarSign,
  'external-link': ExternalLink,
  facebook: Facebook,
  'flower-2': Flower2,
  'gamepad-2': Gamepad2,
  'square-arrow-out-up-right': ExternalLink,
  gift: Gift,
  'globe-2': Globe2,
  'hand-coins': HandCoins,
  heart: Heart,
  home: Home,
  image: ImageIcon,
  instagram: Instagram,
  'layout-dashboard': LayoutDashboard,
  'layout-list': LayoutList,
  link: Link2,
  'link-2': Link2,
  linkedin: Linkedin,
  list: List,
  mail: Mail,
  map: MapIcon,
  'map-pin': MapPin,
  megaphone: Megaphone,
  'message-circle': MessageCircle,
  music: Music,
  package: Package,
  paintbrush: Paintbrush,
  percent: Percent,
  phone: Phone,
  'qr-code': QrCode,
  receipt: Receipt,
  rocket: Rocket,
  'scan-line': ScanLine,
  settings: Settings,
  'settings-2': Settings2,
  'share-2': Share2,
  'shopping-bag': ShoppingBag,
  sparkles: Sparkles,
  square: Square,
  star: Star,
  store: Store,
  tag: Tag,
  'thumbs-up': ThumbsUp,
  ticket: Ticket,
  trophy: Trophy,
  truck: Truck,
  tv: Tv,
  'user-cog': UserCog,
  'user-round': User,
  user: User,
  users: Users,
  'users-round': Users,
  utensils: Utensils,
  video: Video,
  wallet: Wallet,
  'wand-2': Wand2,
  wifi: Wifi,
  wrench: Wrench,
  youtube: Youtube,
  zap: Zap,
}

/**
 * Names offered in the icon picker. Curated rather than `Object.keys(ICONS)`,
 * because the map holds aliases that render identically — listing all of them
 * would show the same glyph three times.
 */
export const ONEQR_ICON_CHOICES = [
  'check',
  'circle-check',
  'calendar-days',
  'calendar-check',
  'calendar-clock',
  'clock',
  'home',
  'building-2',
  'store',
  'list',
  'settings-2',
  'layout-dashboard',
  'layout-list',
  'briefcase',
  'dollar-sign',
  'badge-dollar-sign',
  'credit-card',
  'wallet',
  'hand-coins',
  'receipt',
  'heart',
  'star',
  'thumbs-up',
  'award',
  'trophy',
  'gift',
  'crown',
  'percent',
  'ticket',
  'tag',
  'megaphone',
  'bell',
  'sparkles',
  'zap',
  'rocket',
  'user-round',
  'user-cog',
  'users-round',
  'bot',
  'phone',
  'mail',
  'message-circle',
  'globe-2',
  'map',
  'qr-code',
  'scan-line',
  'map-pin',
  'link',
  'share-2',
  'square-arrow-out-up-right',
  'camera',
  'image',
  'video',
  'music',
  'tv',
  'gamepad-2',
  'instagram',
  'facebook',
  'linkedin',
  'youtube',
  'shopping-bag',
  'package',
  'truck',
  'car',
  'bike',
  'coffee',
  'utensils',
  'chef-hat',
  'cake',
  'flower-2',
  'paintbrush',
  'wand-2',
  'wrench',
  'wifi',
  'square',
]

export function resolveOneQrIcon(name?: string | null): LucideIcon {
  if (!name) return Square
  return ICONS[name.trim().toLowerCase()] ?? Square
}

export default function OneQrModuleIcon({
  name,
  iconUrl,
  className = 'h-4 w-4',
}: {
  name?: string | null
  /** Merchant-uploaded icon image. Renders in place of `name` when set. */
  iconUrl?: string | null
  className?: string
}) {
  if (iconUrl) {
    return (
      <img
        src={iconUrl}
        alt=""
        aria-hidden
        className={`${className} rounded object-cover`}
      />
    )
  }
  const Icon = resolveOneQrIcon(name)
  return <Icon className={className} aria-hidden />
}
