import { createContext, type PropsWithChildren, useContext, useEffect, useRef, useState } from "react";
import { AlertTriangle, ChevronDown, ShieldCheck } from "lucide-react";
import { Button, Card, Checkbox, Input, Sheet, useToast } from "../../components";
import { storeActions, useStore } from "../../store";

type Deferred = { actionId: string; run: () => void } | null;
type GateApi = { requireAccount: (actionId: string, run: () => void) => void; requireConsent: (actionId: string, run: () => void) => void; openTerms: () => void };
const GateContext = createContext<GateApi>({ requireAccount: () => undefined, requireConsent: () => undefined, openTerms: () => undefined });
export function useCommunityGate() { return useContext(GateContext); }

const TERM_TITLES = ["Bên cung cấp dịch vụ (NEXORA TOUCH LLC)", "Điều kiện tham gia", "Nội dung của bạn", "Hành vi bị cấm", "Việc làm, ca làm thêm & giao dịch giữa thành viên", "Tin nhắn, gọi & AI", "Kiểm duyệt", "Khiếu nại bản quyền", "Miễn trừ bảo đảm", "Giới hạn trách nhiệm", "Bồi hoàn", "Giải quyết tranh chấp", "Thay đổi điều khoản", "Ngôn ngữ", "Liên hệ"];
const CONSENT_CHECKS = ["Tôi xác nhận đã đủ 18 tuổi.", "Tôi đã đọc Điều khoản sử dụng Community.", "Tôi hiểu NEXORA là nền tảng kết nối, không bảo đảm giao dịch giữa thành viên.", "Tôi đồng ý với Nội quy cộng đồng NEXORA."];

function AccountSheet({ open, close, deferred }: { open: boolean; close: () => void; deferred: Deferred }) {
  const toast = useToast(); const otpEnabled = useStore((state) => state.otpEnabled);
  const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [agreed, setAgreed] = useState(false); const [expanded, setExpanded] = useState(false); const [errors, setErrors] = useState<Record<string, string>>({}); const [otp, setOtp] = useState(false);
  const submit = () => { const next: Record<string, string> = {}; if (name.trim().length < 2) next.name = "Nhập tên hiển thị"; if (phone.replace(/\D/g, "").length < 7) next.phone = "Nhập số điện thoại hợp lệ"; if (!agreed) next.agreed = "Cần đồng ý điều khoản để tạo tài khoản"; setErrors(next); if (Object.keys(next).length) return; if (phone.replace(/\D/g, "") === "7135553107") { setErrors({ phone: "SĐT này đã đăng ký" }); return; } if (otpEnabled) { setOtp(true); return; } finish(); };
  const finish = () => { storeActions.createGuestAccount(name, phone); close(); toast("✓ Đã tạo tài khoản — tiếp tục việc bạn đang làm", "success"); if (deferred) window.setTimeout(deferred.run, 400); };
  if (otp) return <Sheet open={open} onClose={close} title="Xác minh OTP"><div className="space-y-5"><p className="rounded-lg bg-nexoraWarning/10 p-3 text-sm text-nexoraText">Chờ Brian chốt có OTP không</p><p className="text-sm text-nexoraMuted">Mã xác minh đã gửi tới {phone}.</p><div className="grid grid-cols-6 gap-2">{Array.from({ length: 6 }, (_, index) => <Input key={index} aria-label={`Chữ số OTP ${index + 1}`} maxLength={1} className="px-0 text-center font-mono" />)}</div><p className="text-sm text-nexoraSubtle">Gửi lại sau 30s</p><Button variant="gradient" className="w-full" onClick={finish}>Xác minh & tiếp tục</Button></div></Sheet>;
  return <Sheet open={open} onClose={close} title="Tạo tài khoản NEXORA · miễn phí"><div className="space-y-4"><p className="text-sm text-nexoraMuted">Chỉ mất một phút. Bạn vẫn xem được mọi thứ nếu chưa sẵn sàng.</p><label className="block text-sm font-semibold">Tên hiển thị<Input value={name} onChange={(event) => setName(event.target.value)} placeholder="Ví dụ: Minh Nguyễn" className="mt-1" /></label>{errors.name && <p className="text-sm text-nexoraDanger">{errors.name}</p>}<label className="block text-sm font-semibold">Số điện thoại<Input value={phone} onChange={(event) => setPhone(event.target.value)} inputMode="tel" placeholder="(713) 555-0100" className="mt-1" /></label>{errors.phone && <p className="text-sm text-nexoraDanger">{errors.phone}{errors.phone === "SĐT này đã đăng ký" && " — đăng nhập bằng OTP"}</p>}<Checkbox checked={agreed} onChange={(event) => setAgreed(event.target.checked)} label="Tôi đủ 18 tuổi, đã đọc và đồng ý Điều khoản sử dụng & Nội quy cộng đồng NEXORA." />{errors.agreed && <p className="text-sm text-nexoraDanger">{errors.agreed}</p>}<button type="button" onClick={() => setExpanded(!expanded)} className="flex min-h-11 items-center gap-1 text-sm font-semibold text-nexoraBrand">Xem 6 điều chính <ChevronDown size={16} /></button>{expanded && <ol className="list-decimal space-y-1 pl-5 text-sm text-nexoraMuted"><li>Bạn chịu trách nhiệm nội dung mình đăng.</li><li>NEXORA chỉ là nền tảng kết nối — không bảo đảm giao dịch giữa thành viên.</li><li>Không chuyển tiền qua tin nhắn — chỉ qua cổng thanh toán trong app.</li><li>Ảnh khách phải có sự đồng ý của khách.</li><li>Không lừa đảo, quấy rối, spam — vi phạm bị gỡ bài, khoá tài khoản.</li><li>AI dịch, phụ đề, cảnh báo chỉ để hỗ trợ.</li></ol>}<div className="grid grid-cols-2 gap-3 pt-2"><Button variant="secondary" onClick={() => { close(); toast("Bạn vẫn xem được mọi thứ — đăng ký khi cần"); }}>Để sau</Button><Button variant="gradient" onClick={submit} disabled={Boolean(name && phone && !agreed)}>Tạo tài khoản & tiếp tục</Button></div></div></Sheet>;
}

function TermsSheet({ open, close, deferred }: { open: boolean; close: () => void; deferred: Deferred }) {
  const toast = useToast(); const termsVersion = useStore((state) => state.termsVersion); const [scrolled, setScrolled] = useState(false); const [checks, setChecks] = useState<boolean[]>([false, false, false, false]); const contentRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!open) { setScrolled(false); setChecks([false, false, false, false]); } }, [open]);
  const agree = () => { storeActions.consent(); close(); toast("✓ Đã tham gia cộng đồng — bản ghi đồng ý đã được lưu", "success"); if (deferred) window.setTimeout(deferred.run, 400); };
  return <Sheet open={open} onClose={close} title={termsVersion === "1.1" ? "Điều khoản đã cập nhật" : "Điều khoản Community"}><div className="space-y-4"><div className="h-1.5 overflow-hidden rounded bg-nexoraBorder"><div className="h-full bg-gradient-to-r from-nexoraElectric to-nexoraViolet" style={{ width: scrolled ? "100%" : "20%" }} /></div><Card className="border-nexoraWarning p-3"><p className="text-xs font-bold text-nexoraText">BẢN NHÁP — CẦN LUẬT SƯ DUYỆT</p><p className="mt-1 text-sm text-nexoraMuted">Nội dung pháp lý đang chờ luật sư hoàn thiện.</p></Card>{termsVersion === "1.1" && <Card className="border-nexoraBrand p-3"><p className="font-bold text-nexoraBrand">Thay đổi so với v1.0</p><p className="mt-1 text-sm text-nexoraMuted">Mục 6a: không chia sẻ tin nhắn thoại/ảnh chụp cuộc gọi của người khác ra ngoài app.</p></Card>}<div ref={contentRef} onScroll={(event) => { const node = event.currentTarget; if (node.scrollTop + node.clientHeight >= node.scrollHeight - 4) setScrolled(true); }} className="max-h-56 overflow-y-auto rounded-lg border border-nexoraBorder p-4">{TERM_TITLES.map((title, index) => <section key={title} className="mb-5"><h3 className="font-bold">{index + 1}. {title}</h3><p className="mt-1 text-sm leading-6 text-nexoraMuted">BẢN NHÁP — CẦN LUẬT SƯ DUYỆT. Điều khoản này mô tả quyền, nghĩa vụ và nguyên tắc sử dụng Community của NEXORA.</p>{index === 5 && termsVersion === "1.1" && <p className="mt-2 text-sm font-semibold">6a. Không chia sẻ tin nhắn thoại/ảnh chụp cuộc gọi của người khác ra ngoài app.</p>}</section>)}</div><div className="space-y-1">{CONSENT_CHECKS.map((label, index) => <Checkbox key={label} checked={checks[index]} onChange={(event) => setChecks((previous) => previous.map((value, itemIndex) => itemIndex === index ? event.target.checked : value))} label={label} />)}</div><div className="grid grid-cols-2 gap-3"><Button variant="secondary" onClick={() => { close(); toast("Bạn đang ở chế độ chỉ xem"); }}>Để sau · chỉ xem</Button><Button variant="gradient" disabled={!scrolled || checks.some((checked) => !checked)} onClick={agree}>Đồng ý & tham gia</Button></div></div></Sheet>;
}

export function GateProvider({ children }: PropsWithChildren) {
  const role = useStore((state) => state.role); const termsVersion = useStore((state) => state.termsVersion); const consentVersion = useStore((state) => state.consentVersion); const [accountOpen, setAccountOpen] = useState(false); const [termsOpen, setTermsOpen] = useState(false); const [deferred, setDeferred] = useState<Deferred>(null);
  const clear = () => { setAccountOpen(false); setTermsOpen(false); setDeferred(null); };
  const api: GateApi = { requireAccount(actionId, run) { if (role === "guest") { setDeferred({ actionId, run }); setAccountOpen(true); return; } if (consentVersion !== termsVersion) { setDeferred({ actionId, run }); setTermsOpen(true); return; } run(); }, requireConsent(actionId, run) { if (consentVersion !== termsVersion) { setDeferred({ actionId, run }); setTermsOpen(true); } else run(); }, openTerms() { setTermsOpen(true); } };
  return <GateContext.Provider value={api}>{children}<AccountSheet open={accountOpen} close={clear} deferred={deferred} /><TermsSheet open={termsOpen} close={clear} deferred={deferred} /></GateContext.Provider>;
}

export function TermsBanner() { const terms = useStore((state) => state.termsVersion); const consent = useStore((state) => state.consentVersion); const { openTerms } = useCommunityGate(); if (terms === consent) return null; return <Card className="mb-4 flex flex-col gap-3 border-nexoraWarning p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><AlertTriangle className="shrink-0 text-nexoraWarning" /><p className="text-sm font-medium">📜 Điều khoản cộng đồng đã cập nhật (v1.1). Vui lòng xem & đồng ý lại để tiếp tục đăng bài.</p></div><Button variant="secondary" onClick={openTerms}>Xem thay đổi</Button></Card>; }

export function ConsentStatus() { const terms = useStore((state) => state.termsVersion); const consent = useStore((state) => state.consentVersion); return <span className="inline-flex items-center gap-1 text-xs text-nexoraMuted"><ShieldCheck size={14} /> Điều khoản {consent === terms ? `v${terms}` : "cần cập nhật"}</span>; }
