import { type ButtonHTMLAttributes, type InputHTMLAttributes, type PropsWithChildren, type ReactNode, type TextareaHTMLAttributes, createContext, useContext, useState } from "react";
import { Check, X } from "lucide-react";

const focus = "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-nexoraBrand/20";
export function Button({ variant = "primary", className = "", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "gradient" | "secondary" | "ghost" | "danger" }) {
  const styles = { primary: "bg-nexoraBrand text-white hover:bg-nexoraBrandDark", gradient: "bg-gradient-to-r from-nexoraElectric to-nexoraViolet text-white", secondary: "border border-nexoraBorder bg-nexoraSurface text-nexoraText hover:bg-nexoraSurfaceMuted", ghost: "text-nexoraMuted hover:bg-nexoraSurfaceMuted", danger: "bg-nexoraDanger text-white" };
  return <button {...props} className={`min-h-11 rounded-flox-buttons px-4 text-sm font-semibold transition ${focus} disabled:cursor-not-allowed disabled:opacity-45 ${styles[variant]} ${className}`} />;
}
export function IconButton({ label, children, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { label: string }) { return <button {...props} aria-label={label} title={label} className={`grid size-11 place-items-center rounded-lg text-nexoraMuted hover:bg-nexoraSurfaceMuted ${focus}`}>{children}</button>; }
export function Card({ children, className = "" }: PropsWithChildren<{ className?: string }>) { return <section className={`rounded-flox-cards border border-nexoraBorder bg-nexoraSurface shadow-nexora-card ${className}`}>{children}</section>; }
export function Badge({ children, tone = "brand" }: PropsWithChildren<{ tone?: "brand" | "success" | "warning" | "danger" | "neutral" }>) { const toneClass = { brand: "bg-nexoraBrandSoft text-nexoraBrand", success: "bg-nexoraSuccess/10 text-nexoraSuccess", warning: "bg-nexoraWarning/10 text-nexoraText", danger: "bg-nexoraDanger/10 text-nexoraDanger", neutral: "bg-nexoraSurfaceMuted text-nexoraMuted" }; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${toneClass[tone]}`}>{children}</span>; }
export const Chip = Badge;
export function Input({ className = "", ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className={`min-h-11 w-full rounded-flox-inputs border border-nexoraBorder bg-nexoraSurface px-3 text-base text-nexoraText placeholder:text-nexoraSubtle ${focus} ${className}`} />; }
export function Textarea({ className = "", ...props }: TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea {...props} className={`w-full rounded-flox-inputs border border-nexoraBorder bg-nexoraSurface p-3 text-base ${focus} ${className}`} />; }
export function Select({ children, className = "", ...props }: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select {...props} className={`min-h-11 w-full rounded-flox-inputs border border-nexoraBorder bg-nexoraSurface px-3 text-base ${focus} ${className}`}>{children}</select>; }
export function Checkbox({ label, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: ReactNode }) { return <label className="flex min-h-11 items-start gap-3 text-sm text-nexoraMuted"><input {...props} type="checkbox" className="mt-1 size-4 accent-nexoraBrand" /><span>{label}</span></label>; }
export function Toggle({ checked, onChange, label }: { checked: boolean; onChange: (next: boolean) => void; label: string }) { return <button type="button" onClick={() => onChange(!checked)} className={`flex min-h-11 w-full items-center justify-between rounded-lg px-3 text-sm ${focus}`}><span>{label}</span><span className={`relative h-6 w-11 rounded-full transition ${checked ? "bg-nexoraBrand" : "bg-nexoraBorder"}`}><span className={`absolute top-1 size-4 rounded-full bg-white transition ${checked ? "left-6" : "left-1"}`} /></span></button>; }
export function RadioCard({ checked, onClick, children }: PropsWithChildren<{ checked: boolean; onClick: () => void }>) { return <button type="button" onClick={onClick} className={`min-h-11 rounded-lg border p-3 text-left ${focus} ${checked ? "border-nexoraBrand bg-nexoraBrandSoft" : "border-nexoraBorder bg-white"}`}>{children}</button>; }
export function Stepper({ step, total }: { step: number; total: number }) { return <div className="flex items-center gap-2">{Array.from({ length: total }, (_, i) => <span key={i} className={`h-2 flex-1 rounded-full ${i < step ? "bg-gradient-to-r from-nexoraElectric to-nexoraViolet" : "bg-nexoraBorder"}`} />)}</div>; }
export function Sheet({ open, onClose, title, children }: PropsWithChildren<{ open: boolean; onClose: () => void; title: string }>) { if (!open) return null; return <div className="fixed inset-0 z-50 flex items-end bg-nexoraText/60 p-0 backdrop-blur-sm lg:items-center lg:justify-center lg:p-6" role="dialog" aria-modal="true"><div className="max-h-[92dvh] w-full overflow-y-auto rounded-t-2xl bg-white shadow-premium lg:max-w-lg lg:rounded-2xl"><header className="sticky top-0 flex items-center justify-between border-b border-nexoraBorder bg-white px-5 py-4"><h2 className="text-lg font-bold">{title}</h2><IconButton label="Đóng" onClick={onClose}><X size={20} /></IconButton></header><div className="p-5">{children}</div></div></div>; }
export const Modal = Sheet;
type Toast = { id: number; text: string; tone: "success" | "danger" | "info" };
const ToastContext = createContext<(text: string, tone?: Toast["tone"]) => void>(() => undefined);
export function ToastProvider({ children }: PropsWithChildren) { const [items, setItems] = useState<Toast[]>([]); const show = (text: string, tone: Toast["tone"] = "info") => { const id = Date.now(); setItems((previous) => [...previous, { id, text, tone }]); window.setTimeout(() => setItems((previous) => previous.filter((item) => item.id !== id)), 3400); }; return <ToastContext.Provider value={show}>{children}<div className="fixed inset-x-4 bottom-20 z-[70] space-y-2 lg:inset-x-auto lg:right-5 lg:top-20 lg:bottom-auto lg:w-96">{items.map((item) => <div key={item.id} className={`rounded-xl border bg-white p-3 text-sm font-medium shadow-premium ${item.tone === "danger" ? "border-nexoraDanger" : "border-nexoraBorder"}`}>{item.text}</div>)}</div></ToastContext.Provider>; }
export function useToast() { return useContext(ToastContext); }
export function Tabs({ items, active, onChange }: { items: string[]; active: string; onChange: (item: string) => void }) { return <div className="flex gap-1 border-b border-nexoraBorder" role="tablist">{items.map((item) => <button key={item} onClick={() => onChange(item)} className={`min-h-11 border-b-2 px-3 text-sm font-semibold ${item === active ? "border-nexoraBrand text-nexoraBrand" : "border-transparent text-nexoraMuted"}`}>{item}</button>)}</div>; }
export function SegmentedPills({ items, active, onChange }: { items: string[]; active: string; onChange: (item: string) => void }) { return <div className="flex gap-2 overflow-x-auto pb-1">{items.map((item) => <button key={item} onClick={() => onChange(item)} className={`min-h-11 shrink-0 rounded-full px-4 text-sm font-semibold ${item === active ? "bg-nexoraBrand text-white" : "border border-nexoraBorder bg-white text-nexoraMuted"}`}>{item}</button>)}</div>; }
export function EmptyState({ title, body }: { title: string; body: string }) { return <Card className="p-8 text-center"><p className="font-bold">{title}</p><p className="mt-2 text-sm text-nexoraMuted">{body}</p></Card>; }
export function Skeleton({ className = "" }: { className?: string }) { return <div className={`animate-pulse rounded-lg bg-nexoraSurfaceMuted ${className}`} />; }
export function Avatar({ name, className = "" }: { name: string; className?: string }) { return <span className={`grid size-10 shrink-0 place-items-center rounded-full bg-gradient-to-br from-nexoraElectric to-nexoraViolet text-sm font-bold text-white ${className}`}>{name.split(" ").map((part) => part[0]).slice(-2).join("")}</span>; }
export function MoneyTag({ children }: PropsWithChildren) { return <span className="inline-flex items-baseline gap-1 font-semibold text-nexoraText">{children}<small className="font-normal text-nexoraSubtle">số mẫu</small></span>; }
export function SponsoredBadge() { return <Badge tone="warning">⭐ Được tài trợ</Badge>; }
export function StatusTimeline({ statuses }: { statuses: string[] }) { return <ol className="space-y-3 border-l-2 border-nexoraBrandSoft pl-4">{statuses.map((status, index) => <li key={status} className="relative text-sm text-nexoraMuted"><span className={`absolute -left-[21px] mt-1 size-2.5 rounded-full ${index === statuses.length - 1 ? "bg-nexoraBrand" : "bg-nexoraBrandSoft"}`} />{status}</li>)}</ol>; }
export function QrPlaceholder() { return <svg viewBox="0 0 100 100" className="size-32 rounded-lg border border-nexoraBorder bg-white p-3" aria-label="Mã QR mẫu"><path fill="currentColor" d="M5 5h28v28H5zm7 7v14h14V12zM67 5h28v28H67zm7 7v14h14V12zM5 67h28v28H5zm7 7v14h14V74zM45 5h9v9h-9zm0 18h9v18h-9zm13 13h9v9h-9zm9 9h9v9h-9zm18 0h10v10H85zm-40 18h9v9h-9zm13 9h18v9H58zm27 0h10v18H85z" /></svg>; }
export function PlaceholderImage({ label = "NEXORA" }: { label?: string }) { return <div className="flex aspect-[16/9] items-center justify-center rounded-lg bg-gradient-to-br from-nexoraBrandSoft via-nexoraSurfaceMuted to-nexoraLavender/50 text-sm font-bold text-nexoraBrand"><span>{label}</span></div>; }
export function InlineSuccess({ children }: PropsWithChildren) { return <span className="inline-flex items-center gap-1 text-nexoraSuccess"><Check size={15} />{children}</span>; }
