import {
  WorkOrderTicketStatus,
  type WorkOrderSalonMock,
  type WorkOrderServiceLineMock,
  type WorkOrderTicketMock,
} from './constants'

export enum WorkOrderSalonId {
  Downtown = 'nexora-downtown',
  Lakeside = 'nexora-lakeside',
}

export const WORK_ORDER_SALON_MOCKS: WorkOrderSalonMock[] = [
  {
    id: WorkOrderSalonId.Downtown,
    name: 'Nexora Downtown',
    address: '214 W 5th Street, Austin',
  },
  {
    id: WorkOrderSalonId.Lakeside,
    name: 'Nexora Lakeside',
    address: '8300 N FM 620, Austin',
  },
]

const SERVICE_LINE = {
  gelManicure: { id: 'gel-manicure', name: 'Gel Manicure', price: 42, durationMin: 50, isAddOn: false },
  nailArt: { id: 'nail-art', name: 'Nail Art', price: 18, durationMin: 20, isAddOn: true },
  signaturePedicure: { id: 'signature-pedicure', name: 'Signature Pedicure', price: 48, durationMin: 45, isAddOn: false },
  callusTreatment: { id: 'callus-treatment', name: 'Callus Treatment', price: 22, durationMin: 15, isAddOn: true },
  classicManicure: { id: 'classic-manicure', name: 'Classic Manicure', price: 30, durationMin: 30, isAddOn: false },
  gelPolish: { id: 'gel-polish', name: 'Gel Polish', price: 18, durationMin: 20, isAddOn: true },
  dipPowder: { id: 'dip-powder', name: 'Dip Powder Full Set', price: 55, durationMin: 60, isAddOn: false },
} as const satisfies Record<string, WorkOrderServiceLineMock>

const MANICURE_PEDICURE_SET: WorkOrderServiceLineMock[] = [
  SERVICE_LINE.gelManicure,
  SERVICE_LINE.nailArt,
  SERVICE_LINE.signaturePedicure,
  SERVICE_LINE.callusTreatment,
  SERVICE_LINE.classicManicure,
]

const WORK_ORDER_NOTE = {
  acetoneAlmond: 'Sensitive to acetone. Prefers rounded almond shape.',
  quietWarm: 'Prefers quiet station. Warm water only.',
  glitterAllergy: 'Allergy to glitter top coat.',
} as const

export const WORK_ORDER_TICKET_MOCKS: WorkOrderTicketMock[] = [
  {
    id: 'wo-downtown-1',
    code: 'WO-1042',
    salonId: WorkOrderSalonId.Downtown,
    time: '09:00',
    customerName: 'Sophia Carter',
    serviceName: 'Gel Manicure + Nail Art',
    status: WorkOrderTicketStatus.Assigned,
    station: '04',
    beeper: 'B12',
    services: MANICURE_PEDICURE_SET,
    notes: WORK_ORDER_NOTE.acetoneAlmond,
  },
  {
    id: 'wo-downtown-2',
    code: 'WO-1043',
    salonId: WorkOrderSalonId.Downtown,
    time: '10:30',
    customerName: 'Sophia Carter',
    serviceName: 'Gel Manicure + Nail Art',
    status: WorkOrderTicketStatus.Assigned,
    station: '04',
    beeper: 'B12',
    services: MANICURE_PEDICURE_SET,
    notes: WORK_ORDER_NOTE.acetoneAlmond,
  },
  {
    id: 'wo-downtown-3',
    code: 'WO-1044',
    salonId: WorkOrderSalonId.Downtown,
    time: '12:00',
    customerName: 'Sophia Carter',
    serviceName: 'Gel Manicure + Nail Art',
    status: WorkOrderTicketStatus.Assigned,
    station: '04',
    beeper: 'B12',
    services: MANICURE_PEDICURE_SET,
    notes: WORK_ORDER_NOTE.acetoneAlmond,
  },
  {
    id: 'wo-downtown-4',
    code: 'WO-1048',
    salonId: WorkOrderSalonId.Downtown,
    time: '14:00',
    customerName: 'Maya Chen',
    serviceName: 'Pedicure + Gel Polish',
    status: WorkOrderTicketStatus.InService,
    station: '02',
    beeper: 'B08',
    services: [SERVICE_LINE.signaturePedicure, SERVICE_LINE.gelPolish],
    notes: WORK_ORDER_NOTE.quietWarm,
  },
  {
    id: 'wo-downtown-5',
    code: 'WO-1051',
    salonId: WorkOrderSalonId.Downtown,
    time: '16:30',
    customerName: 'Liam Park',
    serviceName: 'Classic Manicure',
    status: WorkOrderTicketStatus.Completed,
    station: '01',
    beeper: 'B03',
    services: [SERVICE_LINE.classicManicure],
    notes: null,
  },
  {
    id: 'wo-lakeside-1',
    code: 'WO-2104',
    salonId: WorkOrderSalonId.Lakeside,
    time: '09:15',
    customerName: 'Ava Nguyen',
    serviceName: 'Gel Manicure + Nail Art',
    status: WorkOrderTicketStatus.Assigned,
    station: '03',
    beeper: 'B21',
    services: MANICURE_PEDICURE_SET,
    notes: WORK_ORDER_NOTE.glitterAllergy,
  },
  {
    id: 'wo-lakeside-2',
    code: 'WO-2108',
    salonId: WorkOrderSalonId.Lakeside,
    time: '11:00',
    customerName: 'Noah Kim',
    serviceName: 'Dip Powder Full Set',
    status: WorkOrderTicketStatus.Assigned,
    station: '06',
    beeper: 'B15',
    services: [SERVICE_LINE.dipPowder],
    notes: null,
  },
  {
    id: 'wo-lakeside-3',
    code: 'WO-2112',
    salonId: WorkOrderSalonId.Lakeside,
    time: '13:45',
    customerName: 'Emma Tran',
    serviceName: 'Pedicure + Gel Polish',
    status: WorkOrderTicketStatus.InService,
    station: '05',
    beeper: 'B18',
    services: [SERVICE_LINE.signaturePedicure, SERVICE_LINE.callusTreatment],
    notes: WORK_ORDER_NOTE.acetoneAlmond,
  },
]
